import {
  Button,
  ActionSheet,
  Icon,
  Tab,
  Tabs,
  Swipe,
  SwipeItem,
  Tabbar,
  TabbarItem,
  Field,
  CellGroup,
  Empty,
  Collapse,
  CollapseItem,
  Grid,
  GridItem,
  Cell,
  NavBar,
  Popup,
  ConfigProvider,
  Uploader,
  Calendar,
  Area,
  Cascader,
  DatetimePicker,
  Picker,
  Switch,
} from "vant";
export function vantSetup(app) {
  app.use(Button);
  app.use(ActionSheet);
  app.use(Icon);
  app.use(Tab);
  app.use(Tabs);
  app.use(Swipe);
  app.use(SwipeItem);
  app.use(Tabbar);
  app.use(TabbarItem);
  app.use(Field);
  app.use(CellGroup);
  app.use(Empty);
  app.use(Collapse);
  app.use(CollapseItem);
  app.use(Grid);
  app.use(GridItem);
  app.use(Cell);
  app.use(NavBar);
  app.use(Popup);
  app.use(ConfigProvider);
  app.use(Uploader);
  app.use(Calendar);
  app.use(Area);
  app.use(Cascader);
  app.use(DatetimePicker);
  app.use(Picker);
  app.use(Switch);
}
